import mongoose from 'mongoose'

export default mongoose.model('Estabelecimento', {
      codUnidade: String,
	codCnes: Number,
      codIbge: Number,
	cnpj: String,
      nomeFantasia: String,
	natureza: String,
	tipoUnidade: String,
	esferaAdministrativa: String,
      vinculoSus: String,
      retencao: String,
      fluxoClientela: String,
      origemGeografica: String,
      temAtendimentoUrgencia: String,
      temAtendimentoAmbulatorial: String,
      temCentroCirurgico: String,
      temObstetra: String,
      temNeoNatal: String,
      temDialise: String,
      descricaoCompleta: String,
      tipoUnidadeCnes: String,
      categoriaUnidade: String,
      logradouro: String,
      numero: String,
      bairro: String,
      cidade: String,
      uf: String,
      cep: Number,
      turnoAtendimento: String,
      lat: Number,
      long: Number,
      tempo_medio_espera: Number,
});